#pragma once

// @generated by torchgen/gen.py from enum_tag.h

namespace at {
    // Enum of valid tags obtained from the entries in tags.yaml
    enum class Tag {
        view_copy,
        generated,
        dynamic_output_shape,
        inplace_view
    };
}
