#pragma once

// @generated by torchgen/gen.py from Function.h

#include <ATen/Context.h>
#include <ATen/DeviceGuard.h>
#include <ATen/TensorUtils.h>
#include <ATen/TracerMode.h>
#include <ATen/core/Generator.h>
#include <ATen/core/Reduction.h>
#include <ATen/core/Tensor.h>
#include <c10/core/Scalar.h>
#include <c10/core/Storage.h>
#include <c10/core/TensorOptions.h>
#include <c10/util/Deprecated.h>
#include <c10/util/Optional.h>



#include <ATen/ops/_linalg_solve_ops.h>

namespace at {


// aten::_linalg_solve(Tensor A, Tensor B, *, bool left=True) -> (Tensor result, Tensor LU, Tensor pivots)
TORCH_API inline ::std::tuple<at::Tensor,at::Tensor,at::Tensor> _linalg_solve(const at::Tensor & A, const at::Tensor & B, bool left=true) {
    return at::_ops::_linalg_solve::call(A, B, left);
}

// aten::_linalg_solve.result(Tensor A, Tensor B, *, bool left=True, Tensor(a!) result, Tensor(b!) LU, Tensor(c!) pivots) -> (Tensor(a!) result, Tensor(b!) LU, Tensor(c!) pivots)
TORCH_API inline ::std::tuple<at::Tensor &,at::Tensor &,at::Tensor &> _linalg_solve_out(at::Tensor & result, at::Tensor & LU, at::Tensor & pivots, const at::Tensor & A, const at::Tensor & B, bool left=true) {
    return at::_ops::_linalg_solve_result::call(A, B, left, result, LU, pivots);
}

// aten::_linalg_solve.result(Tensor A, Tensor B, *, bool left=True, Tensor(a!) result, Tensor(b!) LU, Tensor(c!) pivots) -> (Tensor(a!) result, Tensor(b!) LU, Tensor(c!) pivots)
TORCH_API inline ::std::tuple<at::Tensor &,at::Tensor &,at::Tensor &> _linalg_solve_outf(const at::Tensor & A, const at::Tensor & B, bool left, at::Tensor & result, at::Tensor & LU, at::Tensor & pivots) {
    return at::_ops::_linalg_solve_result::call(A, B, left, result, LU, pivots);
}

}
